### ISSUE TITLE
30 images with ground truth part segmentation mask in Exercise dataset.

### ISSUE THREAD

**Issue by chenbys** [Talegqz/unsupervised_co_part_segmentation#1]
Thanks for the excellent work.

However, I wonder that how can I get the 30 images with ground truth part segmentation mask in Exercise dataset.
It seems that the GTs are annotated by PSD, but their project (https://github.com/zhenjia-xu/psd) does not mention this and does not reply issues.

Therefore, it would be great if you can help or directly release the evaluation data and annotations of Exercise dataset.

Thank again.

**Comment by Talegqz** [comment]
Thanks for your attention.
I add the 30 images with mask to ./evaluation_data/.
I hope this helps you.

**Comment by chenbys** [comment]
Thanks.
